// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlN-PaE6DLMworgllKMTpNfO0QiQhqP7M',
    appId: '1:523286577146:web:3c3b56b2e5574d0159ee43',
    messagingSenderId: '523286577146',
    projectId: 'chat-app-43ccb',
    authDomain: 'chat-app-43ccb.firebaseapp.com',
    databaseURL: 'https://chat-app-43ccb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-43ccb.appspot.com',
    measurementId: 'G-BQFQF92BR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjC5QcYtE8_XHpmzcXWqpmrlep_OJfUc',
    appId: '1:523286577146:android:4b2af0b40f6427c459ee43',
    messagingSenderId: '523286577146',
    projectId: 'chat-app-43ccb',
    databaseURL: 'https://chat-app-43ccb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-43ccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5z3F-HHHSewlf4jU04oAt1GFzXf6VIc',
    appId: '1:523286577146:ios:7282e42156e2547359ee43',
    messagingSenderId: '523286577146',
    projectId: 'chat-app-43ccb',
    databaseURL: 'https://chat-app-43ccb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-43ccb.appspot.com',
    iosBundleId: 'com.example.reChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk5z3F-HHHSewlf4jU04oAt1GFzXf6VIc',
    appId: '1:523286577146:ios:7282e42156e2547359ee43',
    messagingSenderId: '523286577146',
    projectId: 'chat-app-43ccb',
    databaseURL: 'https://chat-app-43ccb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-43ccb.appspot.com',
    iosBundleId: 'com.example.reChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlN-PaE6DLMworgllKMTpNfO0QiQhqP7M',
    appId: '1:523286577146:web:1f55116940879c0059ee43',
    messagingSenderId: '523286577146',
    projectId: 'chat-app-43ccb',
    authDomain: 'chat-app-43ccb.firebaseapp.com',
    databaseURL: 'https://chat-app-43ccb-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-43ccb.appspot.com',
    measurementId: 'G-2WYZFMYXC1',
  );
}
